services:
  - type: web
    name: real-time-vts
    runtime: python
    plan: free
    branch: main
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: MODEL_SIZE
        value: tiny
      - key: PYTHON_VERSION
        value: 3.10.13
      
